# Generated by Django 5.2.5 on 2025-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_user', models.CharField()),
                ('cmt_timestamp', models.DateTimeField(auto_now_add=True)),
                ('cmt_content', models.CharField()),
                ('cmt_likes', models.IntegerField()),
            ],
        ),
    ]
