# Generated by Django 5.2.5 on 2025-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comment_cmt_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
