# Generated by Django 5.2.5 on 2025-09-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_liked_by_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmt_likes',
        ),
    ]
