# Generated by Django 5.2.5 on 2025-09-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_follower_remove_user_following_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
